### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by karras** [adfinis-sygroup/ansible-guide#11]
I'm not sure how it's done other sphinx docs but this one uses our own theme (which is maybe based on Read The Docs?).

` Built with Sphinx using a theme provided by Read the Docs. `

It would make sense to change that footer line and point to our Sphinx theme on GitHub in case someone is interested.

**Comment by keachi** [comment]
I think this must be done in the [adsy-sphinx-template](https://github.com/adfinis-sygroup/adsy-sphinx-template), there is no such configuration option in the `conf.py`.
