### ISSUE TITLE
Guide recommends deprecated ansible-roles submodule

### ISSUE THREAD

**Issue by pgassmann** [adfinis-sygroup/ansible-guide#44]
In [GETTING STARTED](https://docs.adfinis-sygroup.ch/public/ansible-guide/getting_started.html) there's following information:

> First of all, you need a project repository. For that, you can just clone this repository or start a new one. As a Git Submodule you should add the [ansible-roles](https://github.com/adfinis-sygroup/ansible-roles) as `roles/`:
> ```
> 
> git init
> git commit -m 'Intial commit.' --allow-empty
> git submodule add https://github.com/adfinis-sygroup/ansible-roles adfinis-roles
> ```

The [ansible-roles](https://github.com/adfinis-sygroup/ansible-roles) repository is archived and deprecated. The deprecation note links back to this guide.

Additionally the text is inconsistent. The text states the module should be added as `roles/` but the code adds it as `adfinis-roles`

**Comment by karras** [comment]
Hi Philipp

Good catch, those are leftovers we haven't cleaned up yet. Basically we switched from a mono roles repo setup to dedicated repositories in order to import them to Ansible Galaxy.
