### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by keachi** [adfinis-sygroup/ansible-guide#49]
During the [major cleanup](https://github.com/adfinis-sygroup/ansible-guide/pull/46) the vagrant files and test environment was deleted. The documentation still describes the [test infrastructure](https://github.com/adfinis-sygroup/ansible-guide/blob/master/doc/test_infrastructure.rst). Is there a new Git repository or where was the test infrastructure moved to?

**Comment by karras** [comment]
I'd suggest to update that section and provide a new way to test everything. IMHO the Makefile should only contain stuff related to building the guidelines, we shouldn't mix the guidelines and role testing. It would make more sense to create a common ansible-testing repository which could contain Molecule, Vagrant, etc. testing stuff.
