### ISSUE TITLE
Add recommendations regarding `listen` directive for handlers

### ISSUE THREAD

**Issue by tongpu** [adfinis-sygroup/ansible-guide#50]
I just realized that Ansible 2.2 added the `listen` directive which should make it easier to trigger multiple handlers at once: https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change

We should think about our recommendations for using this feature and extend the handlers section accordingly.

**Comment by keachi** [comment]
:+1:
